

### Create Payment
POST http://localhost:4000/payment/payment
Content-Type: application/json

{
    "job_id":"972273d8-bdb3-4153-8dad-aba7cdacad4e",
    "amount": 500000,
    "source": "tok_visa",
    "description": "Testing another Payment saving to db"
}



###GET ALL PAYMENTS BY ORDER
GET http://localhost:4500/payment/972273d8-bdb3-4153-8dad-aba7cdacad4e



### Update Payment

PUT http://localhost:4500/payment/:paymentId
Content-Type: application/json

{
    "amount": 1500,
    "description": "Updated payment"
}

### Delete Payment

DELETE http://localhost:4500/payment/:paymentId