###specialist create profile
POST http://localhost:4000/profile/create/
Content-Type: application/json

 {  "specialist_id":"bf8a4b50-1e72-41c2-bec0-51d4d90a2063",
    "role": "Web designer",
    "experience": "5 years",
    "education": "Degree Computer science",
    "languages": "English, French",
    "skills": "web designer in Figma, web developer in Angular",
    "description": "lorem ispum 50",
    "hourlyRate": "$10"
}